version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    #mem_limit: 512M  
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - postgresdata13:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
      #mem_limit: 2048M  
    deploy:
      resources:
        limits:
          memory: 2048M

    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        disable_proxy:
          - downloads
        domain: "tube.sensely.tk"
    depends_on:
      - postgres

# whoogle:
#   image: "benbusby/whoogle-search:latest"
#   container_name: "whoogle"
#   logging:
#       driver: none
#   volumes:
#       - "./config/whoogle/languages.json:/usr/src/app/app/misc/languages.json"
#       - "./config/whoogle/countries.json:/usr/src/app/app/misc/countries.json"
#   environment:
#       - WHOOGLE_ALT_YT=tube.sensely.tk
#         #VIRTUAL_HOST: "sensely.ml,www.sensely.ml"
#         #VIRTUAL_PORT: "5000"
#   restart: "unless-stopped"
#   ports:
#     - "127.0.0.1:5000:5000"


volumes:
  postgresdata13:
